#!/bin/sh

rm -rf mods
mkdir mods

jq -c -r '.sync[] | select(.type == "mod")' sync.json \
  | while read -r line; do
    slug="$(printf '%s' "$line" | jq -r '.name')"
    url="$(printf '%s\n' "$line" | jq -r '.url')"
    version="$(printf '%s\n' "$line" | jq -r '.version')"

    env="$(wget -q -O - "https://api.modrinth.com/v2/project/$slug" | jq -r '.environment[]')"

    printf '%s' "$env" \
      | if grep 'server' > /dev/null; then
        (cd mods; wget -q -O "$slug-$version.jar" "$url")
        printf '%s\n' "downloaded $slug"
      fi
  done

# breaks server-side, isn't properly tagged
rm mods/toadlib-Ljldqqcx.jar
